// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3kM5uiUoswbcigxMv8LBZfzjk0rWmu7g',
    appId: '1:770976894467:web:18555eb2605e0ad7500836',
    messagingSenderId: '770976894467',
    projectId: 'meal-monkey-a7464',
    authDomain: 'meal-monkey-a7464.firebaseapp.com',
    storageBucket: 'meal-monkey-a7464.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jabCZY9yvBGGAkyfIUcpPZXwD8luSo0',
    appId: '1:770976894467:android:4732ade88d101987500836',
    messagingSenderId: '770976894467',
    projectId: 'meal-monkey-a7464',
    storageBucket: 'meal-monkey-a7464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5s1r1I7GZYVy7axWi6aygl5SFBnyHyE',
    appId: '1:770976894467:ios:84e1e45899f53258500836',
    messagingSenderId: '770976894467',
    projectId: 'meal-monkey-a7464',
    storageBucket: 'meal-monkey-a7464.appspot.com',
    iosBundleId: 'com.example.mealMonkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH5s1r1I7GZYVy7axWi6aygl5SFBnyHyE',
    appId: '1:770976894467:ios:84e1e45899f53258500836',
    messagingSenderId: '770976894467',
    projectId: 'meal-monkey-a7464',
    storageBucket: 'meal-monkey-a7464.appspot.com',
    iosBundleId: 'com.example.mealMonkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3kM5uiUoswbcigxMv8LBZfzjk0rWmu7g',
    appId: '1:770976894467:web:c6794b4f1d8cbf85500836',
    messagingSenderId: '770976894467',
    projectId: 'meal-monkey-a7464',
    authDomain: 'meal-monkey-a7464.firebaseapp.com',
    storageBucket: 'meal-monkey-a7464.appspot.com',
  );

}